# Generated by Django 4.1.4 on 2022-12-27 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shortener", "0003_shorturlmanager_shorturl_active"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ShortURLManager",
        ),
    ]
